# Generated by Django 6.0.5 on 2026-05-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('pet_name', models.CharField(max_length=100, verbose_name='Кличка питомца')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.service', verbose_name='Какая услуга требуется')),
            ],
        ),
    ]
